version: '3.9'

services:
  web:
    build: .
    container_name: bte_exam_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # для live-reload
    environment:
      - ENV=development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
